### ISSUE TITLE
VirtoCommerce.Catalog does not show update due to 'alpha' PlatformVersion

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-modules#5]
The VirtoCommerce.Catalog module does not show any available updates in the Virtocommerce platform. I think it is related to the fact, that in the modules_v3.json the `PlatformVersion` is set to ```"PlatformVersion": "3.60.0-alpha.11919"``` All other modules have `3.51.0` as PlatformVersion value

**Comment by corneliusmunz** [comment]
I think it is related to a wrong entry in the Virtocommerce.Catalog Module manifest file: https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/src/VirtoCommerce.CatalogModule.Web/module.manifest

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7473 has been created

**Comment by Vectorfield4** [comment]
Hi, @corneliusmunz!
Your problem fixed in the releases:
Platform - https://github.com/VirtoCommerce/vc-platform/releases/tag/3.62.0
Catalog module - https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.48.0

I suppose this resolves your problem, so I closing the issue. Feel free to reopen the issue if it`s not.

**Comment by corneliusmunz** [comment]
Hi @Vectorfield4! Many thanks for that ultra fast response and fix. Unfortunately we have Platform Version 3.51.0 installed (without the SemVer compatibility check) and want to update the modules. Is Platform Version 3.62.0 really required by the new versions of the catalog module? Without the fix in the platform release i can not see any updates of the catalog modules with your changes. Now i could 

* Update Platform to 3.62.0 and afterwards update to the new catalog module
* Update Catalog Module "manually" by uploading a zip file

Both options are not really "good" ones. Do you have any other suggestions? So overall i like the speed in which you update all the repositories but sometimes it is to fast for me as customer :wink:

**Comment by tatarincev** [comment]
Hi @corneliusmunz! Since the latest Catalog module uses some new improvements are introduced in the platform version 3.62, the Catalog module won't work with  3.51 that you have installed,  therefore you have to update the platform before update modules. 

But there are also alternatives depends on your needs:

- In case you only want to update the catalog module because it contains some important fixes or improvements, we can publish a hot-fix for the version compatible with your platform version 3.51.

- In case if you want to update all virto packages but this process scares you :scream: , we have good news, we made the update process for the platform and modules less painful for our customers.  Now you can update all virto dependencies by one command execution [read more how to use vc-build CLI for packages management](https://github.com/VirtoCommerce/vc-platform/blob/master/docs/CLI-tools/package-management.md)
In your case, one command execution will be enough :metal:

```console
vc-build update
```
